### ISSUE TITLE
What are packages needed

### ISSUE THREAD

**Issue by Tripp-collins** [gebwyd/pingr#1]
What packages are needed to run

**Comment by hackermondev** [comment]
he said he wont help you run it lol

**Comment by hackermondev** [comment]
it's easy to figure out if you have ever made a bot before

**Comment by wolfff21123** [comment]
> 

Bruh just discord package lol
pip install discord

**Comment by vo1x** [comment]
> What packages are needed to run

You only need to have `discord.py` afaik.
# To install it:
- `pip install discord.py`

**Comment by MagonYT** [comment]
> > What packages are needed to run
> 
> You only need to have `discord.py` afaik.
> 
> #### To install it: `pip install discord.py`

If you have homebrew then you can just do

'brew install discord'

**Comment by Errordev00** [comment]
There is a requirements.txt file which means that you can just do
`pip install -r requirements.txt`
to install the required dependencies
