### ISSUE TITLE
Closed my old issue but still dont work

### ISSUE THREAD

**Issue by faulty-teen** [gebwyd/pingr#10]
did what i was told in my closed one but still getting with open("config.json") as f:
filenotfounderror: [errono 2] no such file or directory: 'config.json'

**Comment by faulty-teen** [comment]
and i filled in the stuff in config.json

**Comment by G-eb** [comment]
Did you follow the whole video? Make sure you have extracted all the files from the .zip file. If not make sure that main.py and config.json are in the same folder. Feel free to reply if neither of these worked and I will response asap.

**Comment by faulty-teen** [comment]
sorry for late response, yes, it is all in the same folder and they were all extracted but I can't find the video, I didn't find this from the video I saw it when i was just browsing github.

**Comment by vilewired** [comment]
You should send a screenshot of how the files look like in your folder:
eg.
![image](https://github.com/G-eb/pingr/assets/85312115/7c8564c5-492f-4438-8822-1ee66cb51b77)
And also how exactly you execute the script

**Comment by G-eb** [comment]
> sorry for late response, yes, it is all in the same folder and they were all extracted but I can't find the video, I didn't find this from the video I saw it when i was just browsing github.

You can view the video here: https://youtu.be/Y6r0BuVxkh0
