### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by CattopyTheWeb** [gebwyd/pingr#12]
I have made a docker image that can be used to deploy this.
Here is the docker hub link: https://hub.docker.com/repository/docker/cattopy/pingr
To run it you just need to set these environment variables:
`TOKEN`, `ROLEID`, `GUILDID`
I thought I'd let you know, @G-eb

**Comment by CattopyTheWeb** [comment]
Maybe you can make a video about it :)

**Comment by G-eb** [comment]
Nice work, I probably won't make a video on it just because I have some other stuff planned in the future.
Feel free to add me on discord: Geb#1337

**Comment by CattopyTheWeb** [comment]
> Nice work, I probably won't make a video on it just because I have some other stuff planned in the future. Feel free to add me on discord: Geb#1337

It says that the friend request failed.
Maybe add me? Catt0py The Web#6884

**Comment by G-eb** [comment]
I have sent you one :)
