### ISSUE TITLE
/ping doesn't work

### ISSUE THREAD

**Issue by CattopyTheWeb** [gebwyd/pingr#5]
when I do `/ping` I get this error:
`Traceback (most recent call last):
  File "/home/container/spam.py", line 32, in <module>
    @pingr.slash_command(guild_ids=[guildid])
     ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'slash_command'. Did you mean: 'add_command'?`

**Comment by G-eb** [comment]
you're probably not using py-cord, which is the fork of discord.py that pingr was made with.

**Comment by CattopyTheWeb** [comment]
Oh

**Comment by CattopyTheWeb** [comment]
Yeah it was that. Thanks for your help
