### ISSUE TITLE
python spam.py doesn't work

### ISSUE THREAD

**Issue by 12trtn** [gebwyd/pingr#7]
when I do `python spam.py` I get this error:
```
Traceback (most recent call last):
  File "C:\Users\elfel\Desktop\pingr-main\spam.py", line 13, in <module>
    guildid = int(geb["spam_guild_id"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by 12trtn** [comment]
also my bot continues offline, what can I do?

**Comment by G-eb** [comment]
You need to save the "config.json" file

**Comment by DemonDawn** [comment]
i had the same issue but my pip install -r requirements.txt was showing up with nothing after someone recommended doing pip freeze > requirements.txt 
I did this command and ever since, after doing pip install -r requirements.txt , it now just shows up with nothing and continues to the next line. Even if i try python spam.py it says python: can't open file 'C:\\Users\\[kingk]\\spam.py': [Errno 2] No such file or directory . 
What do i do?

**Comment by DemonDawn** [comment]
> i had the same issue but my pip install -r requirements.txt was showing up with nothing after someone recommended doing pip freeze > requirements.txt I did this command and ever since, after doing pip install -r requirements.txt , it now just shows up with nothing and continues to the next line. Even if i try python spam.py it says python: can't open file 'C:\Users\[REDACTED]\spam.py': [Errno 2] No such file or directory . What do i do?

![image](https://user-images.githubusercontent.com/132730814/236599331-ef9292ac-38ed-4669-bf36-cadeb3731baf.png)

**Comment by DemonDawn** [comment]
> > i had the same issue but my pip install -r requirements.txt was showing up with nothing after someone recommended doing pip freeze > requirements.txt I did this command and ever since, after doing pip install -r requirements.txt , it now just shows up with nothing and continues to the next line. Even if i try python spam.py it says python: can't open file 'C:\Users[REDACTED]\spam.py': [Errno 2] No such file or directory . What do i do?
> 
> ![image](https://user-images.githubusercontent.com/132730814/236599331-ef9292ac-38ed-4669-bf36-cadeb3731baf.png)

so i got it to work but i HAVE to run it in Studios Code. I needed a debug extension and now it works, but only on studios!

**Comment by MrFlamPlum** [comment]
I still cant get it to run.  I saved the file, but it wont work
![image](https://github.com/G-eb/pingr/assets/104644305/d9ba5b65-eae8-4d74-940c-2b202ce893ab)

**Comment by MrFlamPlum** [comment]
> I still cant get it to run. I saved the file, but it wont work ![image](https://user-images.githubusercontent.com/104644305/237230011-d9ba5b65-eae8-4d74-940c-2b202ce893ab.png)

I sent all the code to see if anyone can find the issue

**Comment by DemonDawn** [comment]
> 

Update: It only worked once 😭
I've done the exact same steps and now it won't do it ever again. It just runs once instead of loops it. It doesn't even send the ping when It starts coz it only does that in a loop start like it should do.

**Comment by G-eb** [comment]
> > 
> 
> Update: It only worked once 😭 I've done the exact same steps and now it won't do it ever again. It just runs once instead of loops it. It doesn't even send the ping when It starts coz it only does that in a loop start like it should do.

Hello @DemonDawn. Can you please open a seperate issue so to cause less confusion, you can explain your problem in further detail and include screenshots if possible

**Comment by G-eb** [comment]
> > I still cant get it to run. I saved the file, but it wont work ![image](https://user-images.githubusercontent.com/104644305/237230011-d9ba5b65-eae8-4d74-940c-2b202ce893ab.png)
> 
> I sent all the code to see if anyone can find the issue

This issue was solved here: https://github.com/G-eb/pingr/issues/8#issuecomment-1567223164
