### ISSUE TITLE
python spam.py isnt working

### ISSUE THREAD

**Issue by MrFlamPlum** [gebwyd/pingr#9]
ive saved the file, but it just wont work 
![image](https://github.com/G-eb/pingr/assets/104644305/a4dd0305-b099-486a-9ceb-dbd19f096797)

**Comment by kacorvixon1337** [comment]
![image](https://github.com/G-eb/pingr/assets/86743808/21b6930c-833b-4fab-9ba8-895eccea9fdd)
bro best censure i ever seen

**Comment by G-eb** [comment]
Do the following in the console:
- pip uninstall py-cord
- pip install py-cord

This will update you to the newest py-cord version which will fix this problem. (requirements.txt has also been updated)
